<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jadwal_view_model extends CI_Model
{

    public $table = 'jadwal_view';
    public $id = 'kode';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get all
    function get_by_jenis($idj)
    {
        $this->db->where("id_jenis_ibadah", $idj);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($id_jenis = NULL, $q = NULL)
    {
        if($id_jenis != NULL) {
            $this->db->group_start()
                ->where("id_jenis_ibadah", $id_jenis)
                ->group_end();
        }
        if ($q != NULL) {
            $this->db->group_start();
            $this->db->or_like('kode', $q);
            $this->db->or_like('jenis', $q);
            $this->db->or_like('rayon', $q);
            $this->db->or_like('tgl', $q);
            $this->db->or_like('tempat', $q);
            $this->db->or_like('pemimpin', $q);
            $this->db->group_end();
        }
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get total rows
    function count_all()
    {
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL, $id_jenis = NULL)
    {
        if ($id_jenis != NULL) {
            $this->db->group_start()
                ->where("id_jenis_ibadah", $id_jenis)
                ->group_end();
        }
        if($q!=NULL){
            $this->db->group_start();
            $this->db->or_like('kode', $q);
            $this->db->or_like('jenis', $q);
            $this->db->or_like('rayon', $q);
            $this->db->or_like('tgl', $q);
            $this->db->or_like('tempat', $q);
            $this->db->or_like('pemimpin', $q);
            $this->db->group_end();
        }
        $this->db->order_by($this->id, $this->order);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }
}

/* End of file Jadwal_view_model.php */
/* Location: ./application/models/Jadwal_view_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-08 19:53:08 */
/* http://harviacode.com */