<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Notifikasi_view_model extends CI_Model
{

    public $table = 'notifikasi_view';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get all
    function get_hari_ini()
    {
        $this->db->select("notifikasi_view.*, jadwal_view.kode, jadwal_view.rayon, jadwal_view.tgl, jadwal_view.tempat, jadwal_view.pemimpin, jadwal_view.pesan, jadwal_view.terkirim");
        $this->db->join("jadwal_view", "notifikasi_view.id_jenis_ibadah=jadwal_view.id_jenis_ibadah");
        $this->db->where("jadwal_view.tgl BETWEEN " . strtotime("now") . " AND " . strtotime(date("d-m-Y 23:59:59")), NULL, FALSE);
        $this->db->where("jadwal_view.terkirim", "0");
        $this->db->order_by("jadwal_view.tgl", "ASC");
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        if ($q != NULL) {
            $this->db->or_like('id', $q);
            $this->db->or_like('hp', $q);
            $this->db->or_like('nama', $q);
            $this->db->or_like('id_jenis_ibadah', $q);
            $this->db->or_like('jenis_ibadah', $q);
        }
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        if($q!=NULL) {
            $this->db->or_like('id', $q);
            $this->db->or_like('hp', $q);
            $this->db->or_like('nama', $q);
            $this->db->or_like('id_jenis_ibadah', $q);
            $this->db->or_like('jenis_ibadah', $q);
        }
        $this->db->limit($limit, $start);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
}

/* End of file Notifikasi_view_model.php */
/* Location: ./application/models/Notifikasi_view_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-08 19:53:08 */
/* http://harviacode.com */